Repository JarvisCraft/padla, pull requests merged in 2020-02, with the labels that each got.

#50 Rework Ultimate-Messenger API and related stuff
  java-commons/src/main/java/ru/progrm_jarvis/javacommons/bytecode/asm/AsmUtil.java
  java-commons/src/main/java/ru/progrm_jarvis/javacommons/classload/ClassDefiner.java
  java-commons/src/main/java/ru/progrm_jarvis/javacommons/classload/ClassFactory.java
  java-commons/src/main/java/ru/progrm_jarvis/javacommons/classload/ClassUtil.java
  java-commons/src/main/java/ru/progrm_jarvis/javacommons/classload/GcClassDefiners.java
  java-commons/src/main/java/ru/progrm_jarvis/javacommons/collection/CollectionFactory.java
  java-commons/src/main/java/ru/progrm_jarvis/javacommons/invoke/FullAccessLookupFactories.java
  java-commons/src/main/java/ru/progrm_jarvis/javacommons/invoke/InvokeFactory.java
  java-commons/src/main/java/ru/progrm_jarvis/javacommons/invoke/InvokeUtil.java
  java-commons/src/main/java/ru/progrm_jarvis/javacommons/invoke/LookupFactory.java
  java-commons/src/main/java/ru/progrm_jarvis/javacommons/invoke/MethodHandleInvocationMode.java
  java-commons/src/main/java/ru/progrm_jarvis/javacommons/invoke/SimpleInvokeFactory.java
  java-commons/src/main/java/ru/progrm_jarvis/javacommons/invoke/package-info.java
  java-commons/src/main/java/ru/progrm_jarvis/javacommons/unsafe/UnsafeInternals.java
  java-commons/src/test/java/ru/progrm_jarvis/javacommons/bytecode/asm/AsmUtilTest.java
  java-commons/src/test/java/ru/progrm_jarvis/javacommons/classload/ClassFactoryTest.java
  java-commons/src/test/java/ru/progrm_jarvis/javacommons/invoke/InvokeUtilTest.java
  java-commons/src/test/java/ru/progrm_jarvis/javacommons/invoke/SimpleInvokeFactoryTest.java
  reflector/src/main/java/ru/progrm_jarvis/reflector/invoke/LookupFactory.java
  reflector/src/main/java/ru/progrm_jarvis/reflector/wrapper/invoke/InvokeConstructorWrapper.java
  reflector/src/main/java/ru/progrm_jarvis/reflector/wrapper/invoke/InvokeDynamicFieldWrapper.java
  reflector/src/main/java/ru/progrm_jarvis/reflector/wrapper/invoke/InvokeDynamicMethodWrapper.java
  reflector/src/main/java/ru/progrm_jarvis/reflector/wrapper/invoke/InvokeStaticFieldWrapper.java
  reflector/src/main/java/ru/progrm_jarvis/reflector/wrapper/invoke/InvokeStaticMethodWrapper.java
  reflector/src/test/java/ru/progrm_jarvis/reflector/invoke/LookupFactoryTest.java
  ultimate-messenger/pom.xml
  ultimate-messenger/src/main/java/ru/progrm_jarvis/ultimatemessenger/format/model/AbstractCachingTextModelFactoryBuilder.java
  ultimate-messenger/src/main/java/ru/progrm_jarvis/ultimatemessenger/format/model/AbstractGeneratingTextModelFactoryBuilder.java
  ultimate-messenger/src/main/java/ru/progrm_jarvis/ultimatemessenger/format/model/AsmTextModelFactory.java
  ultimate-messenger/src/main/java/ru/progrm_jarvis/ultimatemessenger/format/model/JavassistTextModelFactory.java
  ultimate-messenger/src/main/java/ru/progrm_jarvis/ultimatemessenger/format/model/SimpleTextModelFactory.java
  ultimate-messenger/src/main/java/ru/progrm_jarvis/ultimatemessenger/format/model/StaticTextModel.java
  ultimate-messenger/src/main/java/ru/progrm_jarvis/ultimatemessenger/format/model/TextModel.java
  ultimate-messenger/src/main/java/ru/progrm_jarvis/ultimatemessenger/format/model/TextModelFactory.java
  ultimate-messenger/src/main/java/ru/progrm_jarvis/ultimatemessenger/format/placeholder/SimplePlaceholders.java
  ultimate-messenger/src/main/java/ru/progrm_jarvis/ultimatemessenger/format/util/StringMicroOptimizationUtil.java
  ultimate-messenger/src/main/java/ru/progrm_jarvis/ultimatemessenger/message/DelegatingMessageList.java
  ultimate-messenger/src/main/java/ru/progrm_jarvis/ultimatemessenger/message/Message.java
  ultimate-messenger/src/main/java/ru/progrm_jarvis/ultimatemessenger/message/MessageList.java
  ultimate-messenger/src/test/java/ru/progrm_jarvis/ultimatemessenger/format/model/AbstractTextModelFactoryTest.java
  ultimate-messenger/src/test/java/ru/progrm_jarvis/ultimatemessenger/format/model/AsmTextModelFactoryTest.java
  ultimate-messenger/src/test/java/ru/progrm_jarvis/ultimatemessenger/format/model/JavassistTextModelFactoryTest.java
  ultimate-messenger/src/test/java/ru/progrm_jarvis/ultimatemessenger/format/model/SimpleTextModelFactoryTest.java
  ultimate-messenger/src/test/java/ru/progrm_jarvis/ultimatemessenger/format/model/StaticTextModelTest.java
  ultimate-messenger/src/test/java/ru/progrm_jarvis/ultimatemessenger/format/placeholder/SimplePlaceholdersTest.java
Labels: enhancement

#60 Codefactor fixes #1
  ultimate-messenger/src/main/java/ru/progrm_jarvis/ultimatemessenger/format/StringFormatter.java
  ultimate-messenger/src/main/java/ru/progrm_jarvis/ultimatemessenger/format/model/AsmTextModelFactory.java
  ultimate-messenger/src/main/java/ru/progrm_jarvis/ultimatemessenger/format/model/DebuggingTextModelFactory.java
  ultimate-messenger/src/main/java/ru/progrm_jarvis/ultimatemessenger/format/model/JavassistTextModelFactory.java
  ultimate-messenger/src/main/java/ru/progrm_jarvis/ultimatemessenger/format/placeholder/SimplePlaceholders.java
  ultimate-messenger/src/test/java/ru/progrm_jarvis/ultimatemessenger/format/model/StaticTextModelTest.java
  ultimate-messenger/src/test/java/ru/progrm_jarvis/ultimatemessenger/format/placeholder/SimplePlaceholdersTest.java
Labels: bug, enhancement

#61 Add Lazy#getInitializedOrNull
  java-commons/src/main/java/ru/progrm_jarvis/javacommons/lazy/Lazy.java
Labels: enhancement, incubator

#62 Create FUNDING.yml
  .github/FUNDING.yml
Labels: enhancement, repository management

#63 Lazy improvements: #getInitializedOrNull()
  java-commons/src/main/java/ru/progrm_jarvis/javacommons/lazy/Lazy.java
Labels: enhancement

#64 Add ThreadLocal Lazy
  java-commons/src/main/java/ru/progrm_jarvis/javacommons/lazy/Lazy.java
Labels: enhancement
