Repository JarvisCraft/padla, pull requests merged in 2022-02, with the labels that each got.

#320 Update and minimize Mergify configuration
  .github/mergify.yml
  .mergify.yml
Labels: CI

#321 Make Mergify respect Analyze check
  .github/mergify.yml
Labels: CI

#322 Update rc version number in security policy
  SECURITY.md
Labels: documentation, good first issue

#325 1.0.0-rc.9
  .github/workflows/codeql-analysis.yaml
  .github/workflows/deploy-release.yaml
  .github/workflows/deploy-snapshot.yaml
  .github/workflows/test.yaml
  SECURITY.md
  java-commons/pom.xml
  java-commons/src/main/java/ru/progrm_jarvis/javacommons/util/function/ThrowingConsumer.java
  padla-bom/pom.xml
  pom.xml
  reflector/pom.xml
  ultimate-messenger/pom.xml
Labels: release-candidate

#332 build: remove redundant `dependencies` from `nexus-staging-maven-plugin` configuration
  pom.xml
Labels: enhancement, dependencies
